/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author AngleOfPeace
 */
public class MainMenu extends javax.swing.JFrame {

    private File file;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    public StringBuilder getMD5(byte[] datafile) throws FileNotFoundException, IOException {
        byte[] byteData = null;
        try {
            byteData = MessageDigest.getInstance("MD5").digest(datafile);
        } catch (NoSuchAlgorithmException e) {
            JOptionPane.showMessageDialog(null, "Can read MD5 " + e);
        }

        return convertByteToHex(byteData);
    }

    public StringBuilder getSHAHash(byte[] datafile) throws FileNotFoundException, IOException {
        byte[] byteData = null;
        try {
            byteData = MessageDigest.getInstance("SHA-1").digest(datafile);
        } catch (NoSuchAlgorithmException e) {
            JOptionPane.showMessageDialog(null, "Can read SHA-1 " + e);
        }
        return convertByteToHex(byteData);
    }

    public StringBuilder convertByteToHex(byte[] data) {
        int i;
        StringBuilder sb = new StringBuilder();
        for (i = 0; i < data.length; i++) {
            sb.append(Integer.toString((data[i] & 0xff) + 0x100, 16).substring(1));
        }
        return sb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Txtfile = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtMD5 = new javax.swing.JTextField();
        TxtSHA1 = new javax.swing.JTextField();
        BtnCS = new javax.swing.JButton();
        BtnBrowse = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TxtOMD5 = new javax.swing.JTextField();
        TxtOSHA1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        MENU = new javax.swing.JMenu();
        MenuRC5 = new javax.swing.JMenuItem();
        MenuRC6 = new javax.swing.JMenuItem();
        MenuRSA = new javax.swing.JMenuItem();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mã hoá");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setText("Đồ Án Mã Hóa");

        jLabel2.setText("Thành viên nhóm:");

        jLabel3.setText("Lại Minh Khôi");

        jLabel4.setText("Trần Linh Thái");

        jLabel5.setText("Trần Văn Đại");

        jLabel6.setText("File");

        jLabel7.setText("MD5");

        Txtfile.setEditable(false);

        jLabel9.setText("SHA1");

        TxtMD5.setEditable(false);

        TxtSHA1.setEditable(false);

        BtnCS.setText("Compare");
        BtnCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCSActionPerformed(evt);
            }
        });

        BtnBrowse.setText("Browse");
        BtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBrowseActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setText("Check File");

        jLabel11.setText("Original File MD5");

        jLabel12.setText("Original File SHA1");

        TxtOMD5.setText("Paste MD5 values to compare");
        TxtOMD5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtOMD5MouseClicked(evt);
            }
        });

        TxtOSHA1.setText("Paste SHA1 values to compare");
        TxtOSHA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtOSHA1MouseClicked(evt);
            }
        });

        MENU.setText("MENU");
        MENU.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        MenuRC5.setText("RC5");
        MenuRC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRC5ActionPerformed(evt);
            }
        });
        MENU.add(MenuRC5);

        MenuRC6.setText("RC6");
        MenuRC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRC6ActionPerformed(evt);
            }
        });
        MENU.add(MenuRC6);

        MenuRSA.setText("RSA");
        MenuRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRSAActionPerformed(evt);
            }
        });
        MENU.add(MenuRSA);

        jMenuBar1.add(MENU);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtMD5)
                            .addComponent(TxtSHA1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Txtfile, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnBrowse))
                            .addComponent(TxtOMD5)
                            .addComponent(TxtOSHA1))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCS)
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Txtfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TxtOMD5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtOSHA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCS)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtMD5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtSHA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuRC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRC6ActionPerformed
        new RC6().setVisible(true);
    }//GEN-LAST:event_MenuRC6ActionPerformed

    private void MenuRC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRC5ActionPerformed
        new RC5().setVisible(true);
    }//GEN-LAST:event_MenuRC5ActionPerformed

    private void MenuRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRSAActionPerformed
        new RSA().setVisible(true);
    }//GEN-LAST:event_MenuRSAActionPerformed

    private void BtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBrowseActionPerformed

        Txtfile.setText("");
        TxtMD5.setText("");
        TxtSHA1.setText("");
        JFileChooser fileChooser = new JFileChooser();
        int selection = fileChooser.showOpenDialog(this);
        try {
            if (selection == JFileChooser.APPROVE_OPTION) {
                file = fileChooser.getSelectedFile();
                byte[] datafile=Files.readAllBytes(file.toPath());
                Txtfile.setText(file.getPath());
                TxtMD5.setText(getMD5(datafile).toString());
                TxtSHA1.setText(getSHAHash(datafile).toString());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "File not selected");
        }
    }//GEN-LAST:event_BtnBrowseActionPerformed

    private void BtnCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCSActionPerformed

        if (TxtMD5.getText().equals(TxtOMD5.getText()) && TxtSHA1.getText().equals(TxtOSHA1.getText())) {
            JOptionPane.showMessageDialog(null, "File MATCHED!!!");
        } else {
            JOptionPane.showMessageDialog(null, "File NOT MATCHED!!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnCSActionPerformed

    private void TxtOMD5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtOMD5MouseClicked
        TxtOMD5.setText("");
    }//GEN-LAST:event_TxtOMD5MouseClicked

    private void TxtOSHA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtOSHA1MouseClicked
        TxtOSHA1.setText("");
    }//GEN-LAST:event_TxtOSHA1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBrowse;
    private javax.swing.JButton BtnCS;
    private javax.swing.JMenu MENU;
    private javax.swing.JMenuItem MenuRC5;
    private javax.swing.JMenuItem MenuRC6;
    private javax.swing.JMenuItem MenuRSA;
    private javax.swing.JTextField TxtMD5;
    private javax.swing.JTextField TxtOMD5;
    private javax.swing.JTextField TxtOSHA1;
    private javax.swing.JTextField TxtSHA1;
    private javax.swing.JTextField Txtfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
